/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.bsi.prog2.paineladocao.view;

/**
 *
 * @author victor
 */
public class DialogFichaAnimal extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogFichaAnimal.class.getName());

    /**
     * Creates new form DialogFichaAnimal
     */
    public DialogFichaAnimal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // Método para receber os dados da TelaPrincipal e mostrar no JDialog
    public void preencherDados(String nome, String especie, String adotante, String[] detalhes, javax.swing.Icon foto) {
        // Supondo que você criou essas labels lá no modo Design do JDialog:
        lblNome.setText(nome);
        lblEspecie.setText("Espécie: " + especie);
        
        if (detalhes != null) {
            lblRaca.setText("Raça: " + detalhes[0]);
            lblIdade.setText("Idade: " + detalhes[1]);
            lblPorte.setText("Porte: " + detalhes[2]);
            lblTemperamento.setText("Temperamento: " + detalhes[3]);
        }
        
        lblAdotante.setText("Adotante: " + adotante);
        
        if (foto != null) {
            lblFoto.setIcon(foto);
            lblFoto.setText(""); // Limpa o texto se tiver foto
        } else {
            lblFoto.setIcon(null);
            lblFoto.setText("Sem Foto");
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        lblPorte = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblTemperamento = new javax.swing.JLabel();
        lblAdotante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFoto.setText("jLabel1");
        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblNome.setText("jLabel2");

        lblEspecie.setText("jLabel3");

        lblRaca.setText("jLabel4");

        lblPorte.setText("jLabel5");

        lblIdade.setText("jLabel6");

        lblTemperamento.setText("jLabel7");

        lblAdotante.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdotante)
                    .addComponent(lblTemperamento)
                    .addComponent(lblIdade)
                    .addComponent(lblPorte)
                    .addComponent(lblRaca)
                    .addComponent(lblEspecie)
                    .addComponent(lblNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(lblEspecie)
                .addGap(18, 18, 18)
                .addComponent(lblRaca)
                .addGap(24, 24, 24)
                .addComponent(lblIdade)
                .addGap(18, 18, 18)
                .addComponent(lblPorte)
                .addGap(18, 18, 18)
                .addComponent(lblTemperamento)
                .addGap(18, 18, 18)
                .addComponent(lblAdotante)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            // Importa o tema e aplica
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Falha ao inicializar o tema moderno.");
        }
        // --------------------------------------------------


        // --- 2. CÓDIGO QUE INICIA A SUA TELA (MANTENHA ESTA PARTE) ---
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogFichaAnimal dialog = new DialogFichaAnimal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdotante;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPorte;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblTemperamento;
    // End of variables declaration//GEN-END:variables
}
