/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.bsi.prog2.paineladocao.view;

import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlAdotantes = new javax.swing.JPanel();
        pnlAnimais = new javax.swing.JPanel();
        lblTituloAnimal = new javax.swing.JLabel();
        lblNomeAnimal = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        lblEspecie = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        lblRaca = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        tblAnimais = new javax.swing.JScrollPane();
        tblListagemAnimais = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));

        pnlAdotantes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAdotantesLayout = new javax.swing.GroupLayout(pnlAdotantes);
        pnlAdotantes.setLayout(pnlAdotantesLayout);
        pnlAdotantesLayout.setHorizontalGroup(
            pnlAdotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        pnlAdotantesLayout.setVerticalGroup(
            pnlAdotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        tabPrincipal.addTab("Adotantes", pnlAdotantes);

        pnlAnimais.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloAnimal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAnimal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAnimal.setText("Cadastro de Animais");

        lblNomeAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeAnimal.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeAnimal.setText("Nome");

        lblEspecie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEspecie.setForeground(new java.awt.Color(0, 0, 0));
        lblEspecie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspecie.setText("Espécie");

        lblRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRaca.setForeground(new java.awt.Color(0, 0, 0));
        lblRaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRaca.setText("Raça");

        txtRaca.addActionListener(this::txtRacaActionPerformed);

        btnSalvar.setText("Salvar");

        tblListagemAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnimais.setViewportView(tblListagemAnimais);

        javax.swing.GroupLayout pnlAnimaisLayout = new javax.swing.GroupLayout(pnlAnimais);
        pnlAnimais.setLayout(pnlAnimaisLayout);
        pnlAnimaisLayout.setHorizontalGroup(
            pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnimaisLayout.createSequentialGroup()
                .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAnimaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEspecie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeAnimal)
                    .addComponent(txtRaca)
                    .addComponent(txtEspecie)))
            .addComponent(tblAnimais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addGroup(pnlAnimaisLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAnimaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
        pnlAnimaisLayout.setVerticalGroup(
            pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnimaisLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTituloAnimal)
                .addGap(18, 18, 18)
                .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAnimal)
                    .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecie)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaca)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabPrincipal.addTab("Animais", pnlAnimais);

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblNomeAnimal;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblTituloAnimal;
    private javax.swing.JPanel pnlAdotantes;
    private javax.swing.JPanel pnlAnimais;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JScrollPane tblAnimais;
    private javax.swing.JTable tblListagemAnimais;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNomeAnimal;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables
}
